



#ifndef __FEIYU_UI_COMMON_H__
#define __FEIYU_UI_COMMON_H__



#define MAX_ITEM_NUM 16+2+1
#define MAX_SHOW_BUFF_LEN 56

typedef struct  FeiyuGlobalSettings_S
{
	HI_CHAR Text[MAX_SHOW_BUFF_LEN];
    HI_RESID Img;
    HI_U32 Type;
    HI_U32 Value;
	
}FeiyuGlobalSettings;



typedef enum E_PHOTO_SETTING_ITEM{
	item_PHOTO_IMAGE_MODE,
	item_PHOTO_SCENE,
	item_PHOTO_EXPOSURE,
	item_PHOTO_SHUTTER,
	item_PHOTO_ISO,
	item_PHOTO_WB,
	item_PHOTO_METER,
	
	MAX_PHOTO_item,
}PHOTO_SETTING_ITEM;

typedef enum E_PHOTOTIMER_SETTING_ITEM{
	item_PHOTOTIMER_IMAGE_MODE,
	item_PHOTOTIMER_SCENE,
	item_PHOTOTIMER_EXPOSURE,
	item_PHOTOTIMER_SHUTTER,
	item_PHOTOTIMER_ISO,
	item_PHOTOTIMER_WB,
	item_PHOTOTIMER_METER,
	
	MAX_PHOTOTIMER_item,
}PHOTOTIMER_SETTING_ITEM;

typedef enum E_PHOTODELAY_SETTING_ITEM{
	item_PHOTODELAY_IMAGE_MODE,
	item_PHOTODELAY_DELAY,
	item_PHOTODELAY_SCENE,
	item_PHOTODELAY_EXPOSURE,
	item_PHOTODELAY_SHUTTER,
	item_PHOTODELAY_ISO,
	item_PHOTODELAY_WB,
	item_PHOTODELAY_METER,
	
	MAX_PHOTODELAY_item,
}PHOTODELAY_SETTING_ITEM;

typedef enum E_MULTIPHOTO_SETTING_ITEM{
	item_MULTIPHOTO_IMAGE_TYPE,
	item_MULTIPHOTO_IMAGE_MODE,
	item_MULTIPHOTO_BURST_TYPE,
	item_MULTIPHOTO_LAPSE_INTERVAL,
	item_MULTIPHOTO_LAPSE_SHUTTER,
	item_MULTIPHOTO_CONTINOUS_RATE,
	
	MAX_MULTIPHOTO_item,
}MULTIPHOTO_SETTING_ITEM;


typedef enum E_VIDEOSNAP_SETTING_ITEM{
	item_VIDEOSNAP_SNAP_MODE,
	item_VIDEOSNAP_SNAP_LAPSE_INTERVAL,
		
	MAX_VIDEOSNAP_item,
}VIDEOSNAP_SETTING_ITEM;







typedef enum E_GLOBALSETTINGS_SUBPAGE
{
	//PHOTO
	SUBPAGE_PHOTO_MODE_PARAM = 0,
	SUBPAGE_PHOTO_PARAM_IMAGE_MODE,
	SUBPAGE_PHOTO_PARAM_SCENE,
	SUBPAGE_PHOTO_PARAM_STYLE,
	SUBPAGE_PHOTO_PARAM_EXPOSURE,
	SUBPAGE_PHOTO_PARAM_SHUTTER,
	SUBPAGE_PHOTO_PARAM_ISO,
	SUBPAGE_PHOTO_PARAM_WB,
	SUBPAGE_PHOTO_PARAM_METER,
	SUBPAGE_PHOTO_LDC,
	SUBPAGE_PHOTO_FILETYPE,
	
	//PHOTO TIMER
	SUBPAGE_PHOTOTIMER_MODE_PARAM,//8
	SUBPAGE_PHOTOTIMER_PARAM_DELAY_TIME,
	SUBPAGE_PHOTOTIMER_PARAM_IMAGE_MODE,
	//SUBPAGE_PHOTOTIMER_PARAM_SCENE,
	SUBPAGE_PHOTOTIMER_PARAM_STYLE,	
	SUBPAGE_PHOTOTIMER_PARAM_EXPOSURE,
	SUBPAGE_PHOTOTIMER_PARAM_SHUTTER,
	SUBPAGE_PHOTOTIMER_PARAM_ISO,
	SUBPAGE_PHOTOTIMER_PARAM_WB,
	SUBPAGE_PHOTOTIMER_PARAM_METER,
	SUBPAGE_PHOTOTIMER_LDC,
	//SUBPAGE_PHOTOTIMER_FILETYPE,	

	//PHOTODELAY
	SUBPAGE_PHOTODELAY_MODE_PARAM,
	SUBPAGE_PHOTODELAY_PARAM_DELAY_TIME,
	SUBPAGE_PHOTODELAY_PARAM_IMAGE_MODE,
	SUBPAGE_PHOTODELAY_PARAM_STYLE,
	SUBPAGE_PHOTODELAY_PARAM_EXPOSURE,
	SUBPAGE_PHOTODELAY_PARAM_SHUTTER,
	SUBPAGE_PHOTODELAY_PARAM_ISO,
	SUBPAGE_PHOTODELAY_PARAM_WB,
	SUBPAGE_PHOTODELAY_PARAM_METER,
	SUBPAGE_PHOTODELAY_LDC,

	
	//MULTI PHOTO
	SUBPAGE_MULTIPHOTO_MODE_PARAM,
	SUBPAGE_MULTIPHOTO_BURST_BURSTTYPE,
	SUBPAGE_MULTIPHOTO_BURST_IMAGE_MODE,
	//SUBPAGE_MULTIPHOTO_BURST_SCENE,
	SUBPAGE_MULTIPHOTO_BURST_STYLE,	
	SUBPAGE_MULTIPHOTO_BURST_EXPOSURE,
	//SUBPAGE_MULTIPHOTO_BURST_SHUTTER,
	SUBPAGE_MULTIPHOTO_BURST_ISO,
	SUBPAGE_MULTIPHOTO_BURST_WB,
	SUBPAGE_MULTIPHOTO_BURST_METER,
	//SUBPAGE_MULTIPHOTO_TYPE,
	//SUBPAGE_MULTIPHOTO_LAPSE_IMAGE_MODE,
	//SUBPAGE_MULTIPHOTO_LAPSE_INTERVALTIME,
	//SUBPAGE_MULTIPHOTO_LAPSE_SHUTTER,
	//SUBPAGE_MULTIPHOTO_CONTINUOUS_IMAGE_MODE,//18
	//SUBPAGE_MULTIPHOTO_CONTINUOUS_RATE,
	SUBPAGE_MULTIPHOTO_LDC,

	
	
	//LIVE
	SUBPAGE_LIVE_MODE_PARAM,

	
	//VIDEO SNAP
	SUBPAGE_VIDEOSNAP_MODE_PARAM,
	SUBPAGE_VIDEOSNAP_LAPSEINTERVAL,
	SUBPAGE_VIDEOSNAP_MODE,
	SUBPAGE_VIDEOSNAP_AUDIO,
	//SUBPAGE_VIDEOSNAP_FLIP,
	//SUBPAGE_VIDEOSNAP_OSD,
	SUBPAGE_VIDEOSNAP_ENCODE,
	//SUBPAGE_VIDEOSNAP_VIDEOSYSTEM,
	SUBPAGE_VIDEOSNAP_DIS,
	SUBPAGE_VIDEOSNAP_LDC,
	SUBPAGE_VIDEOSNAP_STYLE,	
	SUBPAGE_VIDEOSNAP_PARAM_EXPOSURE,
	//SUBPAGE_VIDEOSNAP_PARAM_SHUTTER,
	SUBPAGE_VIDEOSNAP_PARAM_ISO,
	SUBPAGE_VIDEOSNAP_PARAM_WB,
	SUBPAGE_VIDEOSNAP_PARAM_METER,
	SUBPAGE_VIDEOSNAP_PARAM_SLOW_FPS,
	SUBPAGE_VIDEOSNAP_PARAM_VENC_RC_MODE,	
	
	//VIDEO
	SUBPAGE_VIDEO_MODE_PARAM,
	SUBPAGE_VIDEO_MODE,
	SUBPAGE_VIDEO_AUDIO,
	//SUBPAGE_VIDEO_FLIP,
	//SUBPAGE_VIDEO_OSD,
	SUBPAGE_VIDEO_ENCODE,
	//SUBPAGE_VIDEO_VIDEOSYSTEM,
	SUBPAGE_VIDEO_DIS,
	SUBPAGE_VIDEO_LDC,
	SUBPAGE_VIDEO_STYLE,	
	SUBPAGE_VIDEO_PARAM_EXPOSURE,
	//SUBPAGE_VIDEO_PARAM_SHUTTER,
	SUBPAGE_VIDEO_PARAM_ISO,
	SUBPAGE_VIDEO_PARAM_WB,
	SUBPAGE_VIDEO_PARAM_METER,
	SUBPAGE_VIDEO_PARAM_SLOW_FPS,
	SUBPAGE_VIDEO_PARAM_VENC_RC_MODE,
	
	////VIDEO LAPSE
	SUBPAGE_VIDEOLAPSE_MODE_PARAM,
	SUBPAGE_VIDEOLAPSE_LAPSEINTERVAL,
	SUBPAGE_VIDEOLAPSE_MODE,
	SUBPAGE_VIDEOLAPSE_AUDIO,
	//SUBPAGE_VIDEOLAPSE_FLIP,
	//SUBPAGE_VIDEOLAPSE_OSD,
	SUBPAGE_VIDEOLAPSE_ENCODE,
	//SUBPAGE_VIDEOLAPSE_VIDEOSYSTEM,
	SUBPAGE_VIDEOLAPSE_DIS,
	SUBPAGE_VIDEOLAPSE_LDC,
	SUBPAGE_VIDEOLAPSE_STYLE,	
	SUBPAGE_VIDEOLAPSE_PARAM_EXPOSURE,
	//SUBPAGE_VIDEOLAPSE_PARAM_SHUTTER,
	SUBPAGE_VIDEOLAPSE_PARAM_ISO,
	SUBPAGE_VIDEOLAPSE_PARAM_WB,
	SUBPAGE_VIDEOLAPSE_PARAM_METER,
	SUBPAGE_VIDEOLAPSE_PARAM_SLOW_FPS,
	SUBPAGE_VIDEOLAPSE_PARAM_VENC_RC_MODE,
	
	//VIDEO SLOW
	SUBPAGE_VIDEOSLOW_MODE_PARAM,
	SUBPAGE_VIDEOSLOW_MODE,
	SUBPAGE_VIDEOSLOW_AUDIO,
	//SUBPAGE_VIDEOSLOW_FLIP,
	//SUBPAGE_VIDEOSLOW_OSD,
	SUBPAGE_VIDEOSLOW_ENCODE,
	//SUBPAGE_VIDEOSLOW_VIDEOSYSTEM,
	SUBPAGE_VIDEOSLOW_DIS,
	SUBPAGE_VIDEOSLOW_LDC,
	SUBPAGE_VIDEOSLOW_STYLE,		
	SUBPAGE_VIDEOSLOW_PARAM_EXPOSURE,
	//SUBPAGE_VIDEOSLOW_PARAM_SHUTTER,
	SUBPAGE_VIDEOSLOW_PARAM_ISO,
	SUBPAGE_VIDEOSLOW_PARAM_WB,
	SUBPAGE_VIDEOSLOW_PARAM_METER,
	SUBPAGE_VIDEOSLOW_PARAM_SLOW_FPS,
	SUBPAGE_VIDEOSLOW_PARAM_RC_MODE,
	
	//VIDEO LOOP
	SUBPAGE_VIDEOLOOP_MODE_PARAM,
	SUBPAGE_VIDEOLOOP_LOOPTYPE,
	SUBPAGE_VIDEOLOOP_MODE,
	SUBPAGE_VIDEOLOOP_AUDIO,
	//SUBPAGE_VIDEOLOOP_FLIP,
	//SUBPAGE_VIDEOLOOP_OSD,
	SUBPAGE_VIDEOLOOP_ENCODE,
	//SUBPAGE_VIDEOLOOP_VIDEOSYSTEM,
	SUBPAGE_VIDEOLOOP_DIS,
	SUBPAGE_VIDEOLOOP_LDC,	
	SUBPAGE_VIDEOLOOP_STYLE,	
	SUBPAGE_VIDEOLOOP_PARAM_EXPOSURE,
	//SUBPAGE_VIDEOLOOP_PARAM_SHUTTER,
	SUBPAGE_VIDEOLOOP_PARAM_ISO,
	SUBPAGE_VIDEOLOOP_PARAM_WB,
	SUBPAGE_VIDEOLOOP_PARAM_METER,
	SUBPAGE_VIDEOLOOP_PARAM_SLOW_FPS,
	SUBPAGE_VIDEOLOOP_PARAM_RC_MODE,

	//GENERAL SETTINGS
	SUBPAGE_GENERAL_SETTINGS_PARAM,//104
	SUBPAGE_GENERAL_SETTINGS_DATE,
	SUBPAGE_GENERAL_SETTINGS_DORMANT_MODE,
	SUBPAGE_GENERAL_SETTINGS_AUTO_OFF,
	SUBPAGE_GENERAL_SETTINGS_FREQ,
	SUBPAGE_GENERAL_SETTINGS_WIFI,
	SUBPAGE_GENERAL_SETTINGS_SD,
	SUBPAGE_GENERAL_SETTINGS_OSD,
	SUBPAGE_GENERAL_SETTINGS_FLIP,
	SUBPAGE_GENERAL_SETTINGS_BLUETOOTH,
	SUBPAGE_GENERAL_SETTINGS_LANGUAGE,
	SUBPAGE_GENERAL_SETTINGS_STARTUP_MODE,
	SUBPAGE_GENERAL_SETTINGS_VIDEO_SYSTEM,
	SUBPAGE_GENERAL_SETTINGS_VOICE,
	SUBPAGE_GENERAL_SETTINGS_BACKLIGHT,
	SUBPAGE_GENERAL_SETTINGS_USB_FUNCTION,
	//SUBPAGE_GENERAL_SETTINGS_LED,
	SUBPAGE_GENERAL_SETTINGS_RESET,
	SUBPAGE_GENERAL_SETTINGS_SW_VERSION_ABOUT,
	//SUBPAGE_GENERAL_SETTINGS_INFO,
	//SUBPAGE_GENERAL_SETTINGS_ABOUT,
	//SUBPAGE_GENERAL_SETTINGS_SW_UPGRADE,

	MAX_SUBPAGE,
	
}GLOBALSETTINGS_SUBPAGE;


typedef struct SubPageItemDes_S
{
	HI_U16 currentPage;
	HI_U16 currentItem;
	HI_U16 strDesID[MAX_ITEM_NUM];
    HI_U16 setCmdid;
    HI_U16 getCmdid;
	HI_U16 FeiyuCmdParam[MAX_ITEM_NUM];
	
}SubPageItemDes;






#endif



